services:
  backend:
    build: ./backend
    container_name: backend-cpa
    restart: always
    ports:
      - "3034:3034"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network


  frontend:
    build: ./frontend
    container_name: frontend-cpa
    restart: always
    environment:
      - API_PROXY_URL=http://backend:3034
    ports:
      - "3050:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db-cpa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: cpa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      # To expose Postgres on the default host port 5432 instead, set POSTGRES_PORT=5432 in your environment.
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
